variables:
  COMPOSER_HOME: /cache/composer

build:
  image: composer
  script:
    - composer install --no-dev --no-interaction
    - |
      cd vendor-bin/box
      composer install --no-interaction
      cd -
      mkdir -p vendor/bin
      ln -s "$(realpath vendor-bin/box/vendor/bin/box)" vendor/bin/box
    - ./bin/platform self:build --no-composer-rebuild --yes --replace-version "$CI_COMMIT_REF_NAME"-"$CI_COMMIT_SHORT_SHA" --output platform.phar
  artifacts:
    expose_as: 'cli-phar'
    paths: ['platform.phar']
