language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
install:
  - composer install --prefer-source --no-interaction
  - composer update --prefer-lowest --no-interaction
script:
  - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-text
