language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

install:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-text
