language: php
dist: trusty
sudo: false

php: nightly
env: TEST_SCRIPT=scripts/test/unit.sh

matrix:
  include:
    - php: 7.1
      env: TEST_SCRIPT=scripts/test/security.sh
    - php: 7.2
      env: TEST_SCRIPT=scripts/test/security.sh

    - php: 7.1
      env: TEST_SCRIPT=scripts/test/installer.sh

    - php: 7.1
      env: TEST_SCRIPT=scripts/test/unit.sh
    - php: 7.2
      env: TEST_SCRIPT=scripts/test/unit.sh
    - php: nightly
      env: TEST_SCRIPT=scripts/test/unit.sh

    - php: 7.2
      env: TEST_SCRIPT=scripts/test/slow.sh

  allow_failures:
    - php: nightly
    - env: TEST_SCRIPT=scripts/test/slow.sh

  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

install:
  - composer install --no-interaction
  - composer global require 'drush/drush:^8.0'

env:
  - PLATFORMSH_CLI_DRUSH=$HOME/.composer/vendor/bin/drush

script: "$TEST_SCRIPT"
