# Metadata about the CLI application itself.
application:
  name: 'SensioCloud CLI'
  version: '0.0.15'
  executable: 'sensiocloud'
  package_name: ~
  installer_url: 'https://accounts.sensio.cloud/cli/installer'
  manifest_url: 'https://accounts.sensio.cloud/cli/manifest.json'
  user_config_dir: '.sensiocloud'
  user_state_file: '.sensiocloud/state.json'
  env_prefix: 'SENSIOCLOUD_CLI_'
  tmp_sub_dir: 'sensiocloud-cli-tmp'

  # The default interactive login method: either 'browser' or 'password'.
  # This can be overridden in the user config file.
  login_method: browser

  # Disabled commands.
  disabled_commands:
    - environment:drush
    - local:drush-aliases

# Configuration for working with projects locally.
local:
  local_dir: '.sensiocloud/local'
  archive_dir: '.sensiocloud/local/build-archives'
  build_dir: '.sensiocloud/local/builds'
  dependencies_dir: '.sensiocloud/local/deps'
  project_config: '.sensiocloud/local/project.yaml'
  project_config_legacy: '.platform-project'
  shared_dir: '.sensiocloud/local/shared'
  web_root: '_www'

  # This can be overridden by the {application.env_prefix}COPY_ON_WINDOWS env
  # var, or via the user config file.
  copy_on_windows: false

# Details about the cloud service that the CLI works with.
service:
  name: 'SensioCloud'
  env_prefix: 'SENSIOCLOUD_'
  header_prefix: 'x-sensiocloud'
  app_config_file: '.sensiocloud.app.yaml'
  project_config_dir: '.sensiocloud'
  docs_url: 'https://sensio.cloud'
  docs_search_url: 'https://www.google.com/search?q=site%3Asensio.cloud%20{{ terms }}'
  accounts_url: 'https://accounts.sensio.cloud'
  pricing_url: ~
  default_from_address: ~
  api_token_help_url: ~
  available_regions:
    - eu.sensio.cloud
  available_plans:
    - development
    - standard
    - medium
    - large

# Configuration relating to API calls.
# This can be overridden in the user config file.
api:
  oauth2_client_id: 'sensio-cloud-cli'
  projects_ttl: 3600
  environments_ttl: 600
  users_ttl: 3600

  # Overridden by {application.env_prefix}ACCOUNTS_API env var.
  accounts_api_url: 'https://accounts.sensio.cloud/api/sensio/'

  # Overridden by {application.env_prefix}DEBUG env var.
  debug: false

  # Overridden by {application.env_prefix}DISABLE_CACHE env var.
  disable_cache: false

  # Overridden by {application.env_prefix}SKIP_SSL env var.
  skip_ssl: false

  # Overridden by {application.env_prefix}SESSION_ID env var.
  session_id: 'default'

# How the CLI detects and configures Git repositories as projects.
detection:
  git_remote_name: 'sensiocloud'
  git_domain: 'sensio.cloud'
  site_domains: ['sensiosite.cloud']

# Automatic updates.
# This can be overridden in the user config file.
updates:
  check_interval: 86400

  # Overridden by {application.env_prefix}UPDATES_CHECK env var.
  check: true
