# Metadata about the CLI application itself.
application:
  name: 'SymfonyCloud (PHP) CLI'
  version: '0.0.24'
  executable: 'symfony-cloud'
  package_name: ~
  installer_url: 'https://a.s5y.io/cli/installer'
  manifest_url: 'https://a.s5y.io/cli/manifest.json'
  user_config_dir: '.symfony-cloud-cli'
  user_state_file: '.symfony-cloud-cli/state.json'
  env_prefix: 'SYMFONY_CLOUD_CLI_'
  tmp_sub_dir: 'symfony-cloud-cli-tmp'
  github_repo: ~
  release_branch: 'master'

  # The default interactive login method: either 'browser' or 'password'.
  # This can be overridden in the user config file.
  login_method: browser

  # The default timezone for times displayed or interpreted by the CLI.
  # An empty (falsy) value here means the PHP or system timezone will be used.
  # For a list of timezones, see: http://php.net/manual/en/timezones.php
  # This can be overridden in the user config file.
  timezone: ~

  # The default date format string. This can be overridden in the user config
  # file, or  by the --date-fmt option. For a list of formats, see:
  # http://php.net/manual/en/function.date.php
  date_format: c

  # Disabled commands (a list of full command names).
  disabled_commands:
    - environment:drush
    - local:drush-aliases

  # Experimental commands (a list of full command names). Enable these in the
  # user config file: the array 'enable_commands' inside the 'experimental'
  # section.
  experimental_commands:
    - project:create

# Configuration for working with projects locally.
local:
  local_dir: '.symfony/local'
  archive_dir: '.symfony/local/build-archives'
  build_dir: '.symfony/local/builds'
  dependencies_dir: '.symfony/local/deps'
  project_config: '.symfony/local/project.yaml'
  project_config_legacy: '.platform-project'
  shared_dir: '.symfony/local/shared'
  web_root: '_www'

  # This can be overridden by the {application.env_prefix}COPY_ON_WINDOWS env
  # var, or via the user config file.
  copy_on_windows: false

# Details about the cloud service that the CLI works with.
service:
  name: 'SymfonyCloud'
  env_prefix: 'SYMFONYCLOUD_'
  header_prefix: 'x-symfonycloud'
  app_config_file: '.symfony.app.yaml'
  project_config_dir: '.symfony'
  docs_url: 'https://symfony.com/doc/cloud'
  docs_search_url: 'https://www.google.com/search?q=site%3Asymfony.com%2Fdoc%2Fcloud%20{{ terms }}'
  accounts_url: 'https://a.s5y.io'
  pricing_url: ~
  default_from_address: ~
  api_token_help_url: ~
  available_regions:
    - eu.s5y.io
  available_plans:
    - development
    - standard
    - medium
    - large

# Configuration relating to API calls.
# This can be overridden in the user config file.
api:
  oauth2_client_id: 'sensio-cloud-cli'
  projects_ttl: 3600
  environments_ttl: 600
  users_ttl: 3600

  # Overridden by {application.env_prefix}ACCOUNTS_API env var.
  accounts_api_url: 'https://a.s5y.io/api/platform/'

  # Overridden by {application.env_prefix}DEBUG env var.
  debug: false

  # Overridden by {application.env_prefix}DISABLE_CACHE env var.
  disable_cache: false

  # Overridden by {application.env_prefix}SKIP_SSL env var.
  skip_ssl: false

  # Overridden by {application.env_prefix}SESSION_ID env var.
  session_id: 'default'

# How the CLI detects and configures Git repositories as projects.
detection:
  git_remote_name: 'symfonycloud'
  git_domain: 's5y.io'
  site_domains: ['sensiosite.cloud', 's5y.io']

# Automatic updates.
# This can be overridden in the user config file.
updates:
  # The interval between automatic update checks (in seconds). 604800 = 7 days.
  check_interval: 604800

  # Overridden by {application.env_prefix}UPDATES_CHECK env var.
  check: true
