services:
    api:
        class:     '\Platformsh\Cli\Api'
        arguments: ['@config']
    config:
        class:     '\Platformsh\Cli\CliConfig'
    drush:
        class:     '\Platformsh\Cli\Service\Drush'
        arguments: ['@config', '@shell']
    fs:
        class:     '\Platformsh\Cli\Service\Filesystem'
        arguments: ['@input', '@output']
    git:
        class:     '\Platformsh\Cli\Service\Git'
        arguments: ['@shell']
    local.project:
        class:     '\Platformsh\Cli\Local\LocalProject'
        arguments: ['@config']
    property_formatter:
        class:     '\Platformsh\Cli\Service\PropertyFormatter'
        arguments: ['@input']
    question_helper:
        class:     '\Platformsh\Cli\Service\QuestionHelper'
        arguments: ['@input', '@output']
    relationships:
        class:     '\Platformsh\Cli\Service\Relationships'
        arguments: ['@output', '@ssh']
    self_updater:
        class:     '\Platformsh\Cli\Service\SelfUpdater'
        arguments: ['@input', '@output', '@config', '@question_helper']
    shell:
        class:     '\Platformsh\Cli\Service\Shell'
        arguments: ['@output']
    ssh:
        class:     '\Platformsh\Cli\Service\Ssh'
        arguments: ['@input', '@output']
    table:
        class:     '\Platformsh\Cli\Service\Table'
        arguments: ['@input', '@output']
    url:
        class:     '\Platformsh\Cli\Service\Url'
        arguments: ['@shell']
