# Services are classes providing functionality needed in multiple places.
#
# See https://symfony.com/doc/current/service_container.html
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Set up all classes in src/Command as console commands.
    Platformsh\Cli\Command\:
        resource: '../src/Command/*'
        tags: [console.command]
        public: false

    # Set up all classes in src/Service as services automatically.
    Platformsh\Cli\Service\:
        resource: '../src/Service/*'

    Platformsh\Cli\Local\LocalProject: {}

    # Aliases @todo remove these
    table: '@Platformsh\Cli\Service\Table'
    config: '@Platformsh\Cli\Service\Config'
    question_helper: '@Platformsh\Cli\Service\QuestionHelper'

    # Configure the cache service.
    cache:
        class:     '\Doctrine\Common\Cache\CacheProvider'
        factory:   'Platformsh\Cli\Service\CacheFactory:createCacheProvider'
        arguments: ['@Platformsh\Cli\Service\Config']
    Doctrine\Common\Cache\CacheProvider: '@cache'

    # Configure the input and output services.
    output:
        class: '\Symfony\Component\Console\Output\ConsoleOutput'
        public: true
    Symfony\Component\Console\Output\OutputInterface: '@output'
    input:
        class: '\Symfony\Component\Console\Input\ArgvInput'
        public: true
    Symfony\Component\Console\Input\InputInterface: '@input'
